### ISSUE TITLE
Silent Mode

### ISSUE THREAD

**Issue by Persiflage** [frolv/kbm#2]
Add a -s flag to silence
"KEYPRESS: _
OPERATION: _"
 messages in the command line.

Not necessarily just a flag either, this should be a feature in the full-sized application.

**Comment by frolv** [comment]
Those are actually debugging messages - not a feature of the program.
All the current precompiled releases I have given out have been compiled in debugging mode so that the testers can see what's happening.

If you wish to get rid of the print statements, simply remove the -DKBM_DEBUG flag from CFLAGS in the Makefile and recompile the program.

**Comment by Persiflage** [comment]
Fair enough, thanks for the clarification.
